### ISSUE TITLE
Getting script path: "cd + pwd" vs. "pushd + pwd + popd"

### ISSUE THREAD

**Issue by nomaed** [arnonzilca/p4u#3]
Was just playing with shell scripts, and I tried to find the difference between using the two methods to get the current directory:
```bash
SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
```
vs.
```bash
pushd $(dirname "${BASH_SOURCE[0]}")
SCRIPT_PATH=$PWD
popd
```

They do the same, and you won't see any difference normally.

However(!) if you source the script (`. ~/some/dir/script.sh`) instead of running it in a sub-shell, you'll end up inside of the script's directory after it finishes executing, no matter where you ran it from.
This is quite undesirable usually.

So, would you like it if I'll change the path getting mechanism in the scripts?

**Comment by arnonzilca** [comment]
right.
we could use this instead:
`SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd && cd - > /dev/null)"`

what do you think?

**Comment by arnonzilca** [comment]
Wish we could put it in p4-help-functions, but it's used to locate p4-help-functions.
catch22

**Comment by arnonzilca** [comment]
btw, the scripts don't contain functions except p4-help-functions, so maybe it isn't such a big deal - why would anyone want to source them?

Also the only relevant SCRIPT_PATH resolution in p4-help-functions is inside a function - so it doesn't run on source.

**Comment by nomaed** [comment]
The scripts don't work without it if the directory is not in the `$PATH`.
I ran it several times directly, i.e. `~/scripts/p4u/p4-show`, and it couldn't source `p4-help-functions` this way.
So I guess that `SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd && cd - > /dev/null)"` would work well.

**Comment by arnonzilca** [comment]
again - we source only p4-help-functions (which is the only script it makes sense to source - even by users), and the only `SCRIPT_PATH` resolution is inside a function in p4-help-functions.
